"use client";

import PageHeader from "@/app/_components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { House, MapPin, Plus } from "lucide-react";
import { useSession } from "next-auth/react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

type WfhRequest = { _id: string; employeeId: string; fromDate: string; toDate: string; dayType: string; reason: string; plannedTasks: string; status: string; reviewRemarks?: string; workLocation: { latitude: number; longitude: number; accuracy?: number; locationName?: string } };
type DeviceChange = { _id: string; employeeId: string; reason: string; status: string; createdAt: string; newDevice?: { deviceType?: string; platform?: string; browser?: string }; requestLocation?: { locationName?: string; latitude?: number; longitude?: number } };
const today = () => new Date().toLocaleDateString("en-CA");

function getGps() { return new Promise<Record<string, unknown>>((resolve, reject) => navigator.geolocation.getCurrentPosition((position) => resolve({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, capturedAt: new Date(position.timestamp).toISOString() }), () => reject(new Error("Fresh GPS is required to register your WFH location.")), { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 })); }

export default function WorkFromHomePage() {
  const { data: session } = useSession(); const role = session?.user?.role; const isManager = role === "MANAGER" || role === "DIRECTOR" || role === "ADMIN";
  const [requests, setRequests] = useState<WfhRequest[]>([]); const [teamRequests, setTeamRequests] = useState<WfhRequest[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [deviceChanges, setDeviceChanges] = useState<DeviceChange[]>([]);
  const [form, setForm] = useState(() => ({ fromDate: today(), toDate: today(), dayType: "FULL_DAY", reason: "", plannedTasks: "" }));
  const load = useCallback(async () => { const ownResponse = await fetch("/api/wfh/requests", { cache: "no-store" }); const own = await ownResponse.json(); if (!ownResponse.ok) throw new Error(own.message); setRequests(own.requests || []); if (isManager) { const [teamResponse, deviceResponse] = await Promise.all([fetch("/api/wfh/requests?team=1", { cache: "no-store" }), fetch("/api/wfh/device-changes?team=1", { cache: "no-store" })]); const team = await teamResponse.json(); const devices = await deviceResponse.json(); if (teamResponse.ok) setTeamRequests(team.requests || []); if (deviceResponse.ok) setDeviceChanges(devices.changes || []); } }, [isManager]);
  useEffect(() => { const initial = window.setTimeout(() => void load().catch((error) => toast.error(error.message)), 0); const timer = window.setInterval(() => void load().catch(() => undefined), 30_000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [load]);
  const submit = async () => { setBusy(true); try { const location = await getGps(); const response = await fetch("/api/wfh/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, ...location }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setOpen(false); await load(); toast.success("WFH request submitted to your manager."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to submit request."); } finally { setBusy(false); } };
  const review = async (id: string, status: "APPROVED" | "REJECTED") => { const remarks = status === "REJECTED" ? window.prompt("Rejection reason") || "" : ""; const response = await fetch(`/api/wfh/requests/${id}/review`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, remarks }) }); const result = await response.json(); if (!response.ok) return toast.error(result.message); await load(); toast.success(`WFH request ${status.toLowerCase()}.`); };
  const reviewDevice = async (id: string, status: "APPROVED" | "REJECTED") => { const remarks = window.prompt(status === "APPROVED" ? "Approval remarks (optional)" : "Rejection reason") || ""; const response = await fetch(`/api/wfh/device-changes/${id}/review`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, remarks }) }); const result = await response.json(); if (!response.ok) return toast.error(result.message); await load(); toast.success(`Device change ${status.toLowerCase()}.`); };
  return <div className="space-y-6 pb-10"><PageHeader title="Work From Home" />
    <div className="flex justify-end"><Button onClick={() => setOpen(true)}><Plus /> Request WFH</Button></div>
    <Card><CardHeader><CardTitle>My requests</CardTitle></CardHeader><CardContent className="space-y-3">{requests.length ? requests.map((item) => <RequestCard key={item._id} item={item} />) : <p className="text-sm text-muted-foreground">No WFH requests.</p>}</CardContent></Card>
    {isManager && <Card><CardHeader><CardTitle>Team approval requests</CardTitle></CardHeader><CardContent className="space-y-3">{teamRequests.length ? teamRequests.map((item) => <div key={item._id} className="rounded-lg border p-4"><RequestCard item={item} />{item.status === "PENDING" && <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => review(item._id, "APPROVED")}>Approve</Button><Button size="sm" variant="destructive" onClick={() => review(item._id, "REJECTED")}>Reject</Button></div>}</div>) : <p className="text-sm text-muted-foreground">No team requests.</p>}</CardContent></Card>}
    {isManager && <Card><CardHeader><CardTitle>WFH device-change requests</CardTitle></CardHeader><CardContent className="space-y-3">{deviceChanges.length ? deviceChanges.map((item) => <div key={item._id} className="rounded-lg border p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium">{item.employeeId} → {item.newDevice?.deviceType || "Device"} / {item.newDevice?.browser || "Browser"}</p><Badge variant={item.status === "REJECTED" ? "destructive" : "secondary"}>{item.status}</Badge></div><p className="mt-2 text-sm">Reason: {item.reason}</p><p className="text-xs text-muted-foreground">{item.requestLocation?.locationName || "Fresh GPS captured"} · {new Date(item.createdAt).toLocaleString()}</p>{item.status === "PENDING" && <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => reviewDevice(item._id, "APPROVED")}>Approve Transfer</Button><Button size="sm" variant="destructive" onClick={() => reviewDevice(item._id, "REJECTED")}>Reject</Button></div>}</div>) : <p className="text-sm text-muted-foreground">No device-change requests.</p>}</CardContent></Card>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Request Work From Home</DialogTitle></DialogHeader><div className="space-y-3"><div className="grid grid-cols-2 gap-2"><Label>From<Input type="date" min={today()} value={form.fromDate} onChange={(event) => setForm({ ...form, fromDate: event.target.value })} /></Label><Label>To<Input type="date" min={form.fromDate} value={form.toDate} onChange={(event) => setForm({ ...form, toDate: event.target.value })} /></Label></div><Label>Day type<select className="mt-1 h-9 w-full rounded-md border bg-transparent px-3" value={form.dayType} onChange={(event) => setForm({ ...form, dayType: event.target.value })}><option value="FULL_DAY">Full day</option><option value="FIRST_HALF">First half</option><option value="SECOND_HALF">Second half</option></select></Label><Label>Reason<Textarea value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></Label><Label>Planned tasks<Textarea value={form.plannedTasks} onChange={(event) => setForm({ ...form, plannedTasks: event.target.value })} /></Label><div className="rounded-md border border-violet-200 bg-violet-50 p-3 text-sm"><MapPin className="mr-2 inline size-4" />Your current GPS becomes the approved WFH work location with a 500 m radius.</div></div><DialogFooter><Button disabled={busy || !form.reason.trim() || !form.plannedTasks.trim()} onClick={submit}>{busy ? "Checking GPS..." : "Submit Request"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function RequestCard({ item }: { item: WfhRequest }) { return <div className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><House className="size-4" /><p className="font-medium">{item.employeeId} · {item.fromDate}{item.toDate !== item.fromDate ? ` to ${item.toDate}` : ""}</p></div><Badge variant={item.status === "REJECTED" ? "destructive" : "secondary"}>{item.status}</Badge></div><p className="mt-2 text-sm">{item.reason}</p><p className="text-sm text-muted-foreground">Tasks: {item.plannedTasks}</p><p className="mt-2 text-xs text-muted-foreground">{item.workLocation.locationName || `${item.workLocation.latitude.toFixed(5)}, ${item.workLocation.longitude.toFixed(5)}`} · {item.dayType.replaceAll("_", " ")}</p>{item.reviewRemarks && <p className="mt-2 text-sm text-red-600">Manager: {item.reviewRemarks}</p>}</div>; }
